apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-service-deployment
  labels:
    app: add-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: add-service
  template:
    metadata:
      labels:
        app: add-service
    spec:
      containers:
      - name: add-service
        image: venkateshm/add-service:2
        ports:
        - containerPort: 80
