apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub-service-deployment
  labels:
    app: sub-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sub-service
  template:
    metadata:
      labels:
        app: sub-service
    spec:
      containers:
      - name: sub-service
        image: venkateshm/sub-service:1
        ports:
        - containerPort: 80
