version: '3'

services:
  addservice:
    image: add-service
    ports:
      - 9001:80
    stdin_open: true
    tty: true
  subservice: 
    image: sub-service
    ports:
      - 9002:80
    stdin_open: true
    tty: true
  calculatorservice:
    image: calculator-service
    ports:
      - 9000:8080
    depends_on:
      - addservice
      - subservice
