apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-service-deployment
  labels:
    app: calculator-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator-service
  template:
    metadata:
      labels:
        app: calculator-service
    spec:
      containers:
      - name: calculator-service
        image: venkateshm/calculator-service:1
        ports:
        - containerPort: 8080
